Traceback (most recent call last):
  File "C:\Users\rubde\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\rubde\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sol = solve_ivp(fun=q_dot,t_span=[t_0, t_f], y0=q0, t_eval=tspan)
# Plotting the solution
plt.plot(sol.t,sol.y[0],label="Displacement")
plt.plot(sol.t,sol.y[1],label="Velocity")
plt.xlabel('Time [s]')
plt.ylabel('Displacement [m] / Velocity [m/s]')
plt.legend()
plt.title("ODe results using solve_ivp")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_121600\2623412041.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0msol[0m [1;33m=[0m [0msolve_ivp[0m[1;33m([0m[0mfun[0m[1;33m=[0m[0mq_dot[0m[1;33m,[0m[0mt_span[0m[1;33m=[0m[1;33m[[0m[0mt_0[0m[1;33m,[0m [0mt_f[0m[1;33m][0m[1;33m,[0m [0my0[0m[1;33m=[0m[0mq0[0m[1;33m,[0m [0mt_eval[0m[1;33m=[0m[0mtspan[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;31m# Plotting the solution[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [0mplt[0m[1;33m.[0m[0mplot[0m[1;33m([0m[0msol[0m[1;33m.[0m[0mt[0m[1;33m,[0m[0msol[0m[1;33m.[0m[0my[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m,[0m[0mlabel[0m[1;33m=[0m[1;34m"Displacement"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mplt[0m[1;33m.[0m[0mplot[0m[1;33m([0m[0msol[0m[1;33m.[0m[0mt[0m[1;33m,[0m[0msol[0m[1;33m.[0m[0my[0m[1;33m[[0m[1;36m1[0m[1;33m][0m[1;33m,[0m[0mlabel[0m[1;33m=[0m[1;34m"Velocity"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mplt[0m[1;33m.[0m[0mxlabel[0m[1;33m([0m[1;34m'Time [s]'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'q_dot' is not defined
NameError: name 'q_dot' is not defined

